easy_admin:
    site_name: 'Admin Panel'
    design:
        menu:
            - { label: 'Homepage', route: 'homepage' }
            - User
            - Article
    search:
        title: 'ssdf'
    entities:
        - App\Entity\Article
        - App\Entity\User
