fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        blog:
            types:
                article:
                    properties:
                        title: ~
                        content: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Article
                        repository: App\Repository\Elastica\ArticleRepository
                        provider: ~
                        finder: ~
