framework:
    secret: '%env(APP_SECRET)%'
    translator: { fallback: '%locale%' }
    default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        prefix_seed: blogger_

        # The app cache caches to the filesystem by default.
        # Other options _include:

        # Redis
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
