twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        user_active_interval: '%app.user_active_interval%'
        image_path: '/uploads/'
    form_themes:
        - 'form/fields.html.twig'
